# Generated by Django 5.2.4 on 2025-07-11 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='page',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pages', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='mechanic',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'mechanic'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tickets', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='page',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pages', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='receptionist',
            field=models.ForeignKey(limit_choices_to={'role': 'receptionist'}, on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to='accounts.profile'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
